# Jenkins Sandbox
version: "3"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins_sandbox
    privileged: true
    user: root
    ports:
      - 9999:8080
      - 50000:50000
    volumes:
      - ${JENKINS_HOME_PATH}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker:/usr/libexec/docker
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: jenkins_sandbox_agent
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
